// eslint-disable-next-line import/no-extraneous-dependencies
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import type { RootState } from '$/index';
import FolderFactory from '#/factorys/folderFactory';
import Folder from '#/folder';

/**
 * Interface for Redux store
 * @interface folderStoreInterface
 * @property {Array<Folder>} folders - Collection of folders
 */
interface folderStoreInterface {
  folders: Array<Folder>;
}

function getFolderStoreFromJson(folderStoreJson: string): Folder[] {
  if (folderStoreJson) {
    const folderStore = JSON.parse(folderStoreJson);
    return folderStore.map((folder: Folder) => new FolderFactory
      .CreateFolderFromJson().factoryMethod(folder));
  }
  return [];
}

/**
 * Initial state for Redux store
 * @type {folderStoreInterface}
 */
const initialState: folderStoreInterface = {
  folders: getFolderStoreFromJson(localStorage.getItem('folderStore') as string) || [],
};

/**
 * Slice for Redux store
 */
const foldersSlice = createSlice({
  name: 'folderStore',
  initialState, // Define initial state
  reducers: {
    /**
     * Add a folder to the collection
     */
    addFolder: (state, action: PayloadAction<Folder>) => {
      state.folders.push(action.payload);
      localStorage.setItem('folderStore', JSON.stringify(state.folders));
    },
    /**
     * Remove a folder from the collection
     */
    removeFolder: (state, action: PayloadAction<Folder>) => {
      state.folders = state.folders.filter((folder) => folder.id !== action.payload.id);
      localStorage.setItem('folderStore', JSON.stringify(state.folders));
    },
    /**
     * Update a folder in the collection
     */
    updateFolder: (state, action: PayloadAction<Folder>) => {
      state.folders = state.folders.map((folder) => {
        if (folder.id === action.payload.id) {
          return action.payload;
        }
        return folder;
      });
      localStorage.setItem('folderStore', JSON.stringify(state.folders));
    },
  },
});

// Export actions generated by "createSlice()":
export const { addFolder, removeFolder, updateFolder } = foldersSlice.actions;

// Export selector generated by "createSlice()":
export const selectFolders = (state: RootState) => state.folderStore.folders;

// Export reducer generated by "createSlice()":
export default foldersSlice.reducer;
