// eslint-disable-next-line import/no-extraneous-dependencies
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import type { RootState } from '$/index';
import Team from '#/team';

/**
 * Interface for Redux store
 * @interface teamtoreInterface
 * @property {Map<string, Team>} teams- Collection of teams
 */
interface teamStoreInterface {
  teams: Map<string, Team>;
}

/**
 * Initial state for Redux store
 * @type {teamStoreInterface}
 */
const initialState: teamStoreInterface = {
  teams: new Map(),
};

/**
 * Slice for Redux store
 */
const teamsSlice = createSlice({
  name: 'teamStore',
  initialState, // Define initial state
  reducers: {
    /**
     * Add a team to the collection
     */
    addTeam: (state, action: PayloadAction<Team>) => {
      state.teams.set(action.payload.id, action.payload);
    },
    /**
     * Remove a team from the collection
     */
    removeTeam: (state, action: PayloadAction<Team>) => {
      state.teams.delete(action.payload.id);
    },
    /**
     * Update a team in the collection
     */
    updateTeam: (state, action: PayloadAction<Team>) => {
      state.teams.set(action.payload.id, action.payload);
    },
  },
});

// Export actions generated by "createSlice()":
export const { addTeam, removeTeam, updateTeam } = teamsSlice.actions;

// Export selector generated by "createSlice()":
export const selectTeams = (state: RootState) => state.teamStore.teams;

// Export reducer generated by "createSlice()":
export default teamsSlice.reducer;
