// eslint-disable-next-line import/no-extraneous-dependencies
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import type { RootState } from '$/index';
import User from '#/user';

/**
 * Interface for Redux store
 * @interface userStoreInterface
 * @property {Map<string, User>} users - Collection of users
 * @property {User} currentUser - Current user
 * @property {string} privateKey - Private key for current user
 */
interface userStoreInterface {
  users: Map<string, User>;
  currentUser: User;
  privateKey: string;
}

/**
 * Initial state for Redux store
 * @type {userStoreInterface}
 */
const initialState: userStoreInterface = {
  users: new Map(),
  currentUser: {} as User,
  privateKey: '456',
};

/**
 * Slice for Redux store
 */
const usersSlice = createSlice({
  name: 'userStore',
  initialState, // Define initial state
  reducers: {
    /**
     * Add a user to the collection
     */
    addUser: (state, action: PayloadAction<User>) => {
      state.users.set(action.payload.id, action.payload);
    },
    /**
     * Remove a user from the collection
     */
    removeUser: (state, action: PayloadAction<User>) => {
      state.users.delete(action.payload.id);
    },
    /**
     * Update a user in the collection
     */
    updateUser: (state, action: PayloadAction<User>) => {
      state.users.set(action.payload.id, action.payload);
    },
    /**
     * Add current user to the collection
     */
    addCurrentUser: (state, action: PayloadAction<User>) => {
      state.currentUser = action.payload;
    },
    /**
     * Remove current user from the collection
     */
    removeCurrentUser: (state) => {
      state.currentUser = {} as User;
    },
    /**
     * Update current user in the collection
     */
    updateCurrentUser: (state, action: PayloadAction<User>) => {
      state.currentUser = action.payload;
    },
    /**
     * Set private key for current user
     */
    setPrivateKey: (state, action: PayloadAction<string>) => {
      state.privateKey = action.payload;
    },
    /**
     * Load private key for current user
     */
    loadPrivateKey: (state) => {
      state.privateKey = localStorage.getItem('privateKey') ?? '';
    },
  },
});

// Export actions generated by "createSlice()":
export const {
  addUser,
  removeUser,
  updateUser,
  addCurrentUser,
  removeCurrentUser,
  updateCurrentUser,
  setPrivateKey,
  loadPrivateKey,
} = usersSlice.actions;

// Export selectors generated by "createSlice()":
export const selectUsers = (state: RootState) => state.userStore.users;
export const selectCurrentUser = (state: RootState) => state.userStore.currentUser;

// Export reducer generated by "createSlice()":
export default usersSlice.reducer;
