name: bump-version
on:
  push:
    branches:
      - "master"

jobs:
  package-json-enforcer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: Wawa27/automatic-version-bump@main