name: bump-version
on:
  push:
    branches:
      - "master"

jobs:
  package-json-enforcer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: thepassle/changelog-enforcer@0.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}