name: Lighthouse
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - name: Npm Install
        run: npm install && npm global add @lhci/cli@0.9.x
      - name: build
        run: 
          npm vite build
      - name: Lighthouse Benchmark
        run: lhci autorun
      - name: Comment PR
