name: Lighthouse
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
      - name: Pnpm Install
        run: pnpm install --no-frozen-lockfile
      - name: Add lhci global
        run: pnpm add --g @lhci/cli@0.9.x
      - name: build
        run: 
          pnpm vite build
      - name: Lighthouse Benchmark
        run: lhci autorun
