name: Lighthouse
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"
      - name: Yarn Install
        env:
          # also other environment variable
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: yarn && yarn global add @lhci/cli@0.9.x
      - name: build
        run: 
          yarn build
      - name: Lighthouse Benchmark
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: "temporary-public-storage"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
