name: "pre-release"
on:
  push:
    branches:
      - "master"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: [ 16 ]
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
      - name: Pnpm Install
        run: pnpm install --no-frozen-lockfile
      - name: Install rust dependencies
        run: /
          sudo apt-get install libgtk-3-dev
          sudo apt install libsoup2.4-dev
          sudo apt-get install javascriptcoregtk-4.0
      - name: build
        run: 
          pnpm tauri build
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
            *.AppImage
            *.snap
            *.exe